version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "learn01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cxq5krstaxic"
s3_prefix = "learn01"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
